export interface CategoriaInfo {
  id: string; // Nombre de la carpeta en public/señas/
  titulo: string; // Título visible en pantalla
  palabras: string[]; // Lista de nombres de archivos (coincide con los videos)
}

export const CATEGORIAS: CategoriaInfo[] = [
  {
    id: "presentacion-1",
    titulo: "Presentación 1 – Presentación y expresión personal",
    palabras: [
      "Hola",
      "Chau",
      //"Buenos días",
      //"Buenas tardes",
      //"Buenas noches",
      //"Yo",
      //"Mi / mío",
      //"Nombre",
      //"Me llamo...",
      //"Soy...",
      //"Tengo ... años",
      //"Vivo en...",
      //"Encantado/a",
      "Gracias",
      "Por favor",
    ],
  },
  {
    id: "presentacion-2",
    titulo: "Presentación 2 – Presentación de otros y preguntas básicas",
    palabras: [
      "Él",
      "Ella",
      "Ellos / ellas",
      "Nosotros",
      "Ustedes",
      "Él es...",
      "Ella es...",
      "Amigo/a",
      "¿Cómo estás?",
      "Bien",
      "Mal",
      "¿De dónde sos?",
      "Más o menos",
      "¿Quién es?",
      "Mucho gusto",
    ],
  },
  {
    id: "familia-y-amigos",
    titulo: "Familia y amigos",
    palabras: [
      "Familia",
      "Mamá",
      "Papá",
      "Hermano",
      "Hermana",
      "Abuelo",
      "Abuela",
      "Tío",
      "Tía",
      "Primo",
      "Prima",
      "Amigo",
      "Amiga",
      "Hijo",
      "Hija",
    ],
  },
  {
    id: "numeros",
    titulo: "Números",
    palabras: [
      "Diez",
      "Veinte",
      "Treinta",
      "Cuarenta",
      "Cincuenta",
      "Sesenta",
      "Setenta",
      "Ochenta",
      "Noventa",
      "Cien",
      "Doscientos",
      "Quinientos",
      "Mil",
      "Dos mil",
      "Un millón",
    ],
  },
  {
    id: "colegio-1",
    titulo: "Colegio 1",
    palabras: [
      "Colegio",
      "Estudiar",
      "Estudiante",
      "Profesor/a",
      "Aula",
      "Recreo",
      "Patio",
      "Libro",
      "Cuaderno",
      "Lápiz",
      "Mochila",
      "Tarea",
      "Examen",
      "Aprender",
      "Preguntar",
    ],
  },
  {
    id: "clima",
    titulo: "Clima",
    palabras: [
      "Clima",
      "Lluvia",
      "Soleado",
      "Nublado",
      "Granizo",
      "Nieve",
      "Frío",
      "Calor",
      "Viento",
      "Tormenta",
      "Niebla",
      "Húmedo",
      "Seco",
      "Embarrado",
      "Temperatura",
    ],
  },
  {
    id: "partes-de-la-casa",
    titulo: "Partes de la casa",
    palabras: [
      "Casa",
      "Puerta",
      "Ventana",
      "Cocina",
      "Baño",
      "Dormitorio",
      "Sala",
      "Comedor",
      "Techo",
      "Piso",
      "Pared",
      "Escalera",
      "Garaje",
      "Jardín",
      "Balcón",
    ],
  },
  {
    id: "preguntas-afuera",
    titulo: "Preguntas afuera / orientación",
    palabras: [
      "¿Dónde está?",
      "¿Hay?",
      "No hay",
      "¿Cómo es?",
      "¿Cuánto?",
      "¿Qué?",
      "¿Quién?",
      "¿Cuándo?",
      "¿Por qué?",
      "¿Cómo?",
      "Acá",
      "Allá",
      "Cerca",
      "Lejos",
      "Ayuda",
    ],
  },
  {
    id: "comprar",
    titulo: "Comprar",
    palabras: [
      "Comprar",
      "Vender",
      "¿Cuánto cuesta?",
      "Precio",
      "Caro",
      "Barato",
      "Tamaño",
      "¿De qué tamaño es?",
      "Talle",
      "Color",
      "Grande",
      "Mediano",
      "Chico",
      "Quiero este/a",
      "Pagar",
    ],
  },
];

// Mapeo directo de ID de categoría a su array de palabras
export const DICCIONARIO_CATEGORIAS: Record<string, string[]> = CATEGORIAS.reduce(
  (acc, cat) => {
    acc[cat.id] = cat.palabras;
    return acc;
  },
  {} as Record<string, string[]>
);

// Función auxiliar para obtener palabras por ID de carpeta
export function getPalabrasPorCategoria(idCategoria: string): string[] {
  return DICCIONARIO_CATEGORIAS[idCategoria] || DICCIONARIO_CATEGORIAS["abecedario"] || [];
}